### ISSUE TITLE
Bug: installing `ufpy` package with `pip`

### ISSUE THREAD

**Issue by bleudev** [honey-team/ufpy#31]
`pip install ufpy` returns:
```
Collecting ufpy
  Using cached ufpy-0.1.1.tar.gz (8.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\aitii\AppData\Local\Temp\pip-install-igg1dzpf\ufpy_820f4621b2014281ac971e9db57b2d70\setup.py", line 3, in <module>
          from ufpy import __version__
        File "C:\Users\aitii\AppData\Local\Temp\pip-install-igg1dzpf\ufpy_820f4621b2014281ac971e9db57b2d70\ufpy\__init__.py", line 5, in <module>
          from .udict import *
        File "C:\Users\aitii\AppData\Local\Temp\pip-install-igg1dzpf\ufpy_820f4621b2014281ac971e9db57b2d70\ufpy\udict.py", line 7, in <module>
          from .typ import AnyDict, AnyCollection
      ModuleNotFoundError: No module named 'ufpy.typ'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by n0n1m** [comment]
This is literally the same issue as #51 but this one was closed despite never being resolved. That's kinda funny
