### ISSUE TITLE
Unable to install module ufpy

### ISSUE THREAD

**Issue by Alexandr153** [honey-team/ufpy#51]
Unable to install module ufpy in PyCharm CE on MacOS with last version of pip and ARM64.

```          
from requests import get
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

- #52

**Comment by n0n1m** [comment]
did you run `pip install -r requirements.txt`? if yes, was there any errors?

**Comment by n0n1m** [comment]
oh, stupuid question, sorry for that

**Comment by moontr3** [comment]
it says `ModuleNotFoundError: No module named 'requests'`, so you'll need to first install the `requests` module. although there could be some other modules you're missing, so I recommend to run `pip install -r requirements.txt` like @n0n1m said, if you haven't already.

if it still doesn't work, check if you're installing the required packages and ufpy in one environment, so for example installing `requests` in a global environment and installing ufpy in a venv will still result in an error

**Comment by n0n1m** [comment]
I think this is a bug that should get fixed. Can you try pip install requests first?

**Comment by n0n1m** [comment]
@bleudev should address this issue anyway

**Comment by Alexandr153** [comment]
<img width="722" alt="Снимок экрана 2024-08-31 в 12 56 59" src="https://github.com/user-attachments/assets/64781d8c-83e6-4846-a067-b0beacfd46c4">
<img width="355" alt="Снимок экрана 2024-08-31 в 12 57 21" src="https://github.com/user-attachments/assets/3fe155c2-aa3d-4afb-a35c-a5355e3d7d5d">

```
Collecting ufpy
  Using cached ufpy-0.2.tar.gz (12 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/Users/alexandrmitin/PycharmProjects/ufpy/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/alexandrmitin/PycharmProjects/ufpy/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alexandrmitin/PycharmProjects/ufpy/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-build-env-jj4328me/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-build-env-jj4328me/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-build-env-jj4328me/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-build-env-jj4328me/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-install-dkxkcs84/ufpy_2ff68897654643c3a9427555ad2100f4/ufpy/__init__.py", line 42, in <module>
          from ufpy.github import *
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-install-dkxkcs84/ufpy_2ff68897654643c3a9427555ad2100f4/ufpy/github/__init__.py", line 2, in <module>
          import ufpy.github.download
        File "/private/var/folders/_f/9ky0n60n0pqf1jqfhsb83p480000gn/T/pip-install-dkxkcs84/ufpy_2ff68897654643c3a9427555ad2100f4/ufpy/github/download.py", line 8, in <module>
          from requests import get
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

**Comment by Alexandr153** [comment]
I'll try to help you.

**Comment by Alexandr153** [comment]
Pull Request #52
